function segment_config_data = make_segment_config_data(mech_type, mech_mass, mech_height, ...
    plat_mass, plat_width, plat_thickness, seg_angle, mech_param)

if nargin == 8
    segment_config_data = struct(...
        'mechanism_type', mech_type, ...
        'mechanism_mass', mech_mass, ...
        'mechanism_height', mech_height, ...
        'platform_mass', plat_mass, ...
        'platform_width', plat_width, ...
        'platform_thickness', plat_thickness, ...
        'segment_angle', seg_angle, ...
        'mechanism_parameters', mech_param);
elseif nargin == 1
    segment_config_data = struct(...
        'mechanism_type', '', ...
        'mechanism_mass', 0, ...
        'mechanism_height', 0, ...
        'platform_mass', 0, ...
        'platform_width', 0, ...
        'platform_thickness', 0, ...
        'segment_angle', 0, ...
        'mechanism_parameters', '');
elseif nargin == 0
    segment_config_data = struct(...
        'mechanism_type', {}, ...
        'mechanism_mass', {}, ...
        'mechanism_height', {}, ...
        'platform_mass', {}, ...
        'platform_width', {}, ...
        'platform_thickness', {}, ...
        'segment_angle', {}, ...
        'mechanism_parameters', {});
else
    error('Incorrect number of inputs.');

end
